import { assetPath } from '../../utils/assetPath';

const img = (path) => assetPath(`assets/img/${path}`);

export const projectPortfolio = [
  {
    id: 'savi',
    title: 'SAVI App',
    subtitle: 'Commerce Platform',
    company: 'Lumi.AI / FreeZoon',
    role: 'Flutter Developer',
    period: 'Production launch',
    status: 'Live product',
    image: img('savi.png'),
    accent: 'linear-gradient(135deg, rgba(255, 198, 53, 0.92), rgba(244, 111, 29, 0.9))',
    summary:
      'A market-facing commerce application shaped around search clarity, product discovery, and smoother order visibility for end users.',
    delivery: [
      'Applied Clean Architecture (MVC) across the app delivery flow.',
      'Built advanced filtering with custom widgets and a seamless search experience.',
      'Added FCM push alerts, wishlist behavior, and real-time order tracking.',
    ],
    seniorLayer: [
      'Search-heavy mobile UX with clearer state handling and scalable catalog behavior.',
      'Production-grade notification flow tied to real commerce events and user actions.',
      'Stronger operational visibility through order status updates and cleaner interaction patterns.',
    ],
    stack: ['Flutter', 'MVC', 'FCM', 'Realtime Tracking', 'Advanced Filtering', 'Wishlist'],
    links: [
      { kind: 'website', label: 'Website', href: 'https://app.savi-mall.com/' },
      { kind: 'google-play', label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.savi.customer' },
    ],
  },
  {
    id: 'qanun-ai',
    title: 'Qanun-ai App',
    subtitle: 'AI Legal Product',
    company: 'Lumi.AI / FreeZoon',
    role: 'Flutter Developer',
    period: 'Professional launch',
    status: 'Web production release',
    image: img('qanoun.jpg'),
    accent: 'linear-gradient(135deg, rgba(255, 187, 76, 0.9), rgba(203, 117, 33, 0.92))',
    summary:
      'A professional production launch for a web-first legal AI product, with release refinement and cleaner notification behavior.',
    delivery: [
      'Supported the production launch for the web app with a more controlled release structure.',
      'Applied Clean Architecture (MVC) to keep product flows clearer and easier to maintain.',
      'Optimized notification systems for a more reliable user communication layer.',
    ],
    seniorLayer: [
      'Production hardening around launch readiness, flow stability, and notification quality.',
      'Architecture decisions shaped to keep the product extensible beyond an MVP-style release.',
      'A stronger alignment between feature delivery, user messaging, and rollout discipline.',
    ],
    stack: ['React', 'Flutter', 'MVC', 'Notifications', 'Launch Hardening', 'Web Product'],
    links: [{ kind: 'website', label: 'Website', href: 'https://qanun-ai.com/' }],
  },
  {
    id: 'patternstock',
    title: 'PatternStock App',
    subtitle: 'Private Product',
    company: 'Lumi.AI / FreeZoon',
    role: 'Flutter Developer',
    period: 'Production delivery',
    status: 'Private release',
    image: null,
    placeholderMonogram: 'PS',
    placeholderLabel: 'Image will be added',
    accent: 'linear-gradient(135deg, rgba(244, 181, 67, 0.92), rgba(153, 82, 25, 0.92))',
    summary:
      'A commerce-oriented mobile product built with dynamic custom interfaces, payment integration, and stronger offline behavior.',
    delivery: [
      'Architected the app using Clean Architecture (MVVM).',
      'Built dynamic custom UIs for product-heavy screens and premium interactions.',
      'Integrated Stripe, FCM push notifications, and offline caching for stronger performance.',
    ],
    seniorLayer: [
      'MVVM-driven delivery for a cleaner feature boundary and easier long-term extension.',
      'Payment and notification flows handled as first-class production concerns, not add-ons.',
      'Offline-aware architecture tuned for real customer behavior and degraded network scenarios.',
    ],
    stack: ['Flutter', 'MVVM', 'Stripe', 'FCM', 'Offline Caching', 'Custom UI'],
    links: [{ kind: 'private', label: 'Private Delivery' }],
  },
  {
    id: 'awa',
    title: 'AWA App',
    subtitle: 'Real Estate Marketplace',
    company: 'AWA Real Estate',
    role: 'Flutter Developer & System Analyst',
    period: 'Market release',
    status: 'Public app stores',
    image: img('awa.png'),
    accent: 'linear-gradient(135deg, rgba(49, 208, 170, 0.92), rgba(14, 116, 96, 0.9))',
    summary:
      'A full-featured real-estate listing application delivered with offline capability, market-ready flows, and production payment handling.',
    delivery: [
      'Built the app with offline caching and local data sourcing for more resilient real-world usage.',
      'Integrated push notifications, OTP authentication, and multiple e-payment rails.',
      'Added richer motion and completed a successful market publication across public stores.',
    ],
    seniorLayer: [
      'Combined product execution with systems analysis to keep requirements and implementation aligned.',
      'Handled e-payment integration as a reliability and checkout experience problem, not only a technical task.',
      'Balanced release quality, richer animation, and operational resilience for a customer-facing launch.',
    ],
    stack: ['Flutter', 'OTP', 'Payments', 'Offline-first', 'Push Notifications', 'System Analysis'],
    links: [
      { kind: 'website', label: 'Website', href: 'https://awa-aqar.com/' },
      { kind: 'google-play', label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.awa.realestatepriv' },
      { kind: 'app-store', label: 'App Store', href: 'https://apps.apple.com/au/app/awa-aqar/id6761497066' },
    ],
  },
  {
    id: 'wasena',
    title: 'Wasena App',
    subtitle: 'Delivery Platform',
    company: 'Regional Logistics Product',
    role: 'Flutter Developer',
    period: 'Earlier launch',
    status: 'Legacy delivery',
    image: img('wasena.jpg'),
    accent: 'linear-gradient(135deg, rgba(255, 196, 61, 0.9), rgba(205, 109, 41, 0.92))',
    summary:
      'A delivery application focused on Damascus countryside users, built to make ordering, tracking, and package receipt faster and more reliable for both residents and local businesses.',
    delivery: [
      'Built customer-facing ordering, tracking, and delivery receipt flows inside one mobile experience.',
      'Shaped the product around local logistics needs instead of a generic store-only interaction model.',
      'Focused the app on dependable everyday delivery behavior and clear package status updates.',
    ],
    seniorLayer: [
      'Structured the product as an operational delivery workflow, not only a storefront interface.',
      'Balanced speed, tracking clarity, and practical UX for repeat usage in a local service context.',
      'Handled the app with product thinking around trust, visibility, and friction reduction in the delivery journey.',
    ],
    stack: ['Flutter', 'Delivery Workflow', 'Order Tracking', 'Customer App', 'Operational UX'],
    links: [{ kind: 'private', label: 'Archived Delivery' }],
  },
  {
    id: 'kk-orders',
    title: 'KK ORDERS App',
    subtitle: 'Operations Workflow',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: 'In-house delivery',
    status: 'Private system',
    image: null,
    placeholderMonogram: 'KO',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(136, 155, 255, 0.92), rgba(80, 107, 214, 0.92))',
    summary:
      'An internal mobile application built to manage and organize fabric order processing for operational teams.',
    delivery: [
      'Independently developed the product in Flutter with Firebase.',
      'Structured the workflow around order organization and processing visibility.',
      'Shipped an internal tool designed to support day-to-day operational throughput.',
    ],
    seniorLayer: [
      'Solo delivery with a practical focus on workflow clarity rather than surface-level UI work only.',
      'A tighter operational product structure to support internal users and repeated process handling.',
      'Built around speed of execution without losing control of maintainability and delivery quality.',
    ],
    stack: ['Flutter', 'Firebase', 'Internal Product', 'Workflow Design', 'Order Management'],
    links: [{ kind: 'private', label: 'In-house Product' }],
  },
  {
    id: 'kk-warehouse',
    title: 'KK GROUP WAREHOUSE Dashboard',
    subtitle: 'Responsive Operations Dashboard',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: 'In-house delivery',
    status: 'Private dashboard',
    image: null,
    placeholderMonogram: 'KW',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(108, 168, 255, 0.9), rgba(46, 96, 194, 0.92))',
    summary:
      'A responsive web dashboard built in Flutter to manage inventory and connect warehouses with the central management hub and sales outlets.',
    delivery: [
      'Built a responsive dashboard in Flutter for fabric and goods inventory management.',
      'Linked warehouses, central management, and sales outlets through one operational interface.',
      'Created a clearer flow for inventory visibility across multiple parts of the business.',
    ],
    seniorLayer: [
      'Treated dashboard delivery as an operational systems problem, not only a frontend task.',
      'Focused on responsive behavior, information clarity, and cross-location visibility.',
      'Structured the product to improve coordination between physical inventory and management control.',
    ],
    stack: ['Flutter Web', 'Responsive Dashboard', 'Inventory', 'Operations', 'Management Visibility'],
    links: [{ kind: 'private', label: 'Private Dashboard' }],
  },
  {
    id: 'zikzak',
    title: 'ZIKZAK App',
    subtitle: 'Retail Ordering App',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: '6-week delivery',
    status: 'Private release',
    image: null,
    placeholderMonogram: 'ZZ',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(247, 198, 41, 0.92), rgba(255, 109, 80, 0.9))',
    summary:
      'A Flutter and Firebase mobile app for handling clothing orders, delivered on a compressed timeline without sacrificing execution quality.',
    delivery: [
      'Delivered the mobile product in one and a half months.',
      'Built the ordering flow using Flutter and Firebase.',
      'Focused on getting a customer-facing retail workflow into production quickly and cleanly.',
    ],
    seniorLayer: [
      'Fast delivery under a short timeline while keeping the solution practical and release-ready.',
      'Balanced implementation speed with enough product discipline to avoid a rushed internal build feel.',
      'Treated ordering flow quality and reliability as core delivery priorities.',
    ],
    stack: ['Flutter', 'Firebase', 'Retail Ordering', 'Fast Delivery', 'Customer Workflow'],
    links: [{ kind: 'private', label: 'Private Release' }],
  },
];
