import { assetPath } from '../../utils/assetPath';

const img = (path) => assetPath(`assets/img/${path}`);

const projectPortfolioItems = [
  {
    id: 'savi',
    title: 'SAVI App',
    subtitle: 'Commerce Platform',
    company: 'Lumi.AI / Free Zone',
    role: 'Flutter Developer',
    period: '03/2025 - Present',
    status: 'Live product',
    image: img('projects-savi.jpg'),
    accent: 'linear-gradient(135deg, rgba(255, 198, 53, 0.92), rgba(244, 111, 29, 0.9))',
    summary:
      'Led and contributed to delivery of a production e-commerce application with advanced filtering, search, FCM notifications, wishlist functionality, and real-time order tracking.',
    delivery: [
      'Delivered advanced filtering and search behavior for a production commerce experience.',
      'Added FCM notifications, wishlist functionality, and real-time order tracking.',
      'Contributed to a release-ready e-commerce application under Lumi.AI / Free Zone delivery.',
    ],
    seniorLayer: [
      'Search-heavy mobile UX with clearer state handling and scalable catalog behavior.',
      'Production-grade notification flow tied to real commerce events and user actions.',
      'Stronger operational visibility through order status updates and cleaner interaction patterns.',
    ],
    stack: ['Flutter', 'MVC', 'FCM', 'Realtime Tracking', 'Advanced Filtering', 'Wishlist'],
    links: [
      { kind: 'website', label: 'SAVI - Website', href: 'https://app.savi-mall.com/' },
      { kind: 'google-play', label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.savi.customer' },
      { kind: 'app-store', label: 'App Store', href: 'https://apps.apple.com/us/app/savi-mall/id6785001568' },
    ],
  },
  {
    id: 'qanun-ai',
    title: 'Qanun-ai App',
    subtitle: 'AI Legal Product',
    company: 'Lumi.AI / Free Zone',
    role: 'Flutter Developer',
    period: '03/2025 - Present',
    status: 'Web production release',
    image: img('projects-qanun-ai.jpg'),
    accent: 'linear-gradient(135deg, rgba(255, 187, 76, 0.9), rgba(203, 117, 33, 0.92))',
    summary:
      'Supported production launch and delivery follow-up for a legal AI product, including notification-system improvements and application structure based on Clean Architecture.',
    delivery: [
      'Supported production launch and delivery follow-up.',
      'Improved the notification system for more reliable user communication.',
      'Structured the application around Clean Architecture.',
    ],
    seniorLayer: [
      'Production hardening around launch readiness, flow stability, and notification quality.',
      'Architecture decisions shaped to keep the product extensible beyond an MVP-style release.',
      'A stronger alignment between feature delivery, user messaging, and rollout discipline.',
    ],
    stack: ['React', 'Flutter', 'MVC', 'Notifications', 'Launch Hardening', 'Web Product'],
    links: [
      { kind: 'website', label: 'Qanun AI - Website', href: 'https://qanun-ai.com/' },
      { kind: 'google-play', label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.lumiai.qanounai' },
    ],
  },
  {
    id: 'patternstock',
    title: 'PatternStock App',
    subtitle: 'Private Product',
    company: 'Lumi.AI / Free Zone',
    role: 'Flutter Developer',
    period: '03/2025 - Present',
    status: 'Private release',
    image: null,
    placeholderMonogram: 'PS',
    placeholderLabel: 'Image will be added',
    accent: 'linear-gradient(135deg, rgba(244, 181, 67, 0.92), rgba(153, 82, 25, 0.92))',
    summary:
      'Architected the application using Clean Architecture with MVVM, built dynamic custom UIs, integrated Stripe payments and FCM notifications, and implemented offline caching.',
    delivery: [
      'Architected the application using Clean Architecture with MVVM.',
      'Built dynamic custom UIs for product-heavy screens.',
      'Integrated Stripe payments, FCM notifications, and offline caching.',
    ],
    seniorLayer: [
      'MVVM-driven delivery for a cleaner feature boundary and easier long-term extension.',
      'Payment and notification flows handled as first-class production concerns, not add-ons.',
      'Offline-aware architecture tuned for real customer behavior and degraded network scenarios.',
    ],
    stack: ['Flutter', 'MVVM', 'Stripe', 'FCM', 'Offline Caching', 'Custom UI'],
    links: [{ kind: 'private', label: 'Private Delivery' }],
  },
  {
    id: 'awa',
    title: 'AWA App',
    subtitle: 'Real Estate Marketplace',
    company: 'AWA Real Estate Company',
    role: 'Flutter Developer and System Analyst',
    period: '01/2025 - Present',
    status: 'Market publication',
    image: img('projects-awa.jpg'),
    accent: 'linear-gradient(135deg, rgba(49, 208, 170, 0.92), rgba(14, 116, 96, 0.9))',
    summary:
      'Built and delivered a full-featured real-estate listing application with offline caching, local data sourcing, push notifications, OTP authentication, Fatora, Syriatel Cash and MTN Cash payment integrations, and custom animations.',
    delivery: [
      'Built offline caching and local data sourcing for resilient real-world usage.',
      'Integrated push notifications, OTP authentication, Fatora, Syriatel Cash, and MTN Cash payments.',
      'Added custom animations and supported delivery through market publication.',
    ],
    seniorLayer: [
      'Combined product execution with systems analysis to keep requirements and implementation aligned.',
      'Handled e-payment integration as a reliability and checkout experience problem, not only a technical task.',
      'Balanced release quality, richer animation, and operational resilience for a customer-facing launch.',
    ],
    stack: ['Flutter', 'OTP', 'Fatora', 'Syriatel Cash', 'MTN Cash', 'Offline Caching', 'System Analysis'],
    links: [
      { kind: 'google-play', label: 'AWA - Google Play', href: 'https://play.google.com/store/apps/details?id=com.awa.realestatepriv' },
      { kind: 'app-store', label: 'App Store', href: 'https://apps.apple.com/au/app/awa-aqar/id6761497066' },
    ],
  },
  {
    id: 'wasena',
    title: 'Wasena App',
    subtitle: 'Delivery Platform',
    company: 'Regional Logistics Product',
    role: 'Flutter Developer',
    period: 'Earlier launch',
    status: 'Legacy delivery',
    image: img('wasena.jpg'),
    accent: 'linear-gradient(135deg, rgba(255, 196, 61, 0.9), rgba(205, 109, 41, 0.92))',
    summary:
      'A delivery application focused on Damascus countryside users, built to make ordering, tracking, and package receipt faster and more reliable for both residents and local businesses.',
    delivery: [
      'Built customer-facing ordering, tracking, and delivery receipt flows inside one mobile experience.',
      'Shaped the product around local logistics needs instead of a generic store-only interaction model.',
      'Focused the app on dependable everyday delivery behavior and clear package status updates.',
    ],
    seniorLayer: [
      'Structured the product as an operational delivery workflow, not only a storefront interface.',
      'Balanced speed, tracking clarity, and practical UX for repeat usage in a local service context.',
      'Handled the app with product thinking around trust, visibility, and friction reduction in the delivery journey.',
    ],
    stack: ['Flutter', 'Delivery Workflow', 'Order Tracking', 'Customer App', 'Operational UX'],
    links: [{ kind: 'private', label: 'Archived Delivery' }],
  },
  {
    id: 'kk-orders',
    title: 'KK ORDERS App',
    subtitle: 'Operations Workflow',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: '07/2023 - 03/2025',
    status: 'Private system',
    image: null,
    placeholderMonogram: 'KO',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(136, 155, 255, 0.92), rgba(80, 107, 214, 0.92))',
    summary:
      'Independently developed a Flutter and Firebase mobile application for managing and organizing fabric order processing.',
    delivery: [
      'Independently developed the product in Flutter with Firebase.',
      'Managed and organized fabric order processing for operational teams.',
      'Structured a private internal workflow around order visibility and delivery control.',
    ],
    seniorLayer: [
      'Solo delivery with a practical focus on workflow clarity rather than surface-level UI work only.',
      'A tighter operational product structure to support internal users and repeated process handling.',
      'Built around speed of execution without losing control of maintainability and delivery quality.',
    ],
    stack: ['Flutter', 'Firebase', 'Internal Product', 'Workflow Design', 'Order Management'],
    links: [{ kind: 'private', label: 'In-house Product' }],
  },
  {
    id: 'kk-warehouse',
    title: 'KK GROUP WAREHOUSE Dashboard',
    subtitle: 'Responsive Operations Dashboard',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: '07/2023 - 03/2025',
    status: 'Private dashboard',
    image: null,
    placeholderMonogram: 'KW',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(108, 168, 255, 0.9), rgba(46, 96, 194, 0.92))',
    summary:
      'Built a responsive Flutter web dashboard for fabric and goods inventory management, connecting warehouses with central management and sales outlets.',
    delivery: [
      'Built a responsive Flutter web dashboard for fabric and goods inventory management.',
      'Linked warehouses, central management, and sales outlets through one operational interface.',
      'Created a clearer flow for inventory visibility across multiple parts of the business.',
    ],
    seniorLayer: [
      'Treated dashboard delivery as an operational systems problem, not only a frontend task.',
      'Focused on responsive behavior, information clarity, and cross-location visibility.',
      'Structured the product to improve coordination between physical inventory and management control.',
    ],
    stack: ['Flutter Web', 'Responsive Dashboard', 'Inventory', 'Operations', 'Management Visibility'],
    links: [{ kind: 'private', label: 'Private Dashboard' }],
  },
  {
    id: 'zikzak',
    title: 'ZIKZAK App',
    subtitle: 'Retail Ordering App',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: '07/2023 - 03/2025',
    status: 'Private release',
    image: null,
    placeholderMonogram: 'ZZ',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(247, 198, 41, 0.92), rgba(255, 109, 80, 0.9))',
    summary:
      'Delivered a Flutter and Firebase mobile application for customer clothing orders within one and a half months.',
    delivery: [
      'Delivered the mobile product in one and a half months.',
      'Built the customer clothing order flow using Flutter and Firebase.',
      'Focused on getting a customer-facing retail workflow into production quickly and cleanly.',
    ],
    seniorLayer: [
      'Fast delivery under a short timeline while keeping the solution practical and release-ready.',
      'Balanced implementation speed with enough product discipline to avoid a rushed internal build feel.',
      'Treated ordering flow quality and reliability as core delivery priorities.',
    ],
    stack: ['Flutter', 'Firebase', 'Retail Ordering', 'Fast Delivery', 'Customer Workflow'],
    links: [{ kind: 'private', label: 'Private Release' }],
  },
  {
    id: 'kk-ecommerce',
    title: 'KK GROUP E-COMMERCE App',
    subtitle: 'Company Product Commerce',
    company: 'K&K Group',
    role: 'Flutter Developer',
    period: '07/2023 - 03/2025',
    status: 'Private system',
    image: null,
    placeholderMonogram: 'KE',
    placeholderLabel: 'Project image pending',
    accent: 'linear-gradient(135deg, rgba(247, 198, 41, 0.92), rgba(88, 105, 220, 0.9))',
    summary:
      'Contributed to an e-commerce application for showcasing, selling, and promoting company products.',
    delivery: [
      'Contributed to product-showcase flows for company products.',
      'Supported selling and promotion workflows inside the e-commerce experience.',
      'Worked within K&K Group product delivery alongside ordering and warehouse systems.',
    ],
    seniorLayer: [
      'Connected commerce presentation with practical sales enablement needs.',
      'Kept the product direction aligned with K&K Group business workflows.',
      'Supported a broader internal product ecosystem across orders, warehouse, and sales.',
    ],
    stack: ['Flutter', 'E-commerce', 'Product Catalog', 'Sales Workflow', 'Private System'],
    links: [{ kind: 'private', label: 'Private System' }],
  },
];

const featuredProjectOrder = [
  'savi',
  'qanun-ai',
  'patternstock',
  'awa',
  'kk-orders',
  'kk-warehouse',
  'zikzak',
  'kk-ecommerce',
  'wasena',
];

export const projectPortfolio = featuredProjectOrder
  .map((projectId) => projectPortfolioItems.find((project) => project.id === projectId))
  .filter(Boolean);
